// Actions relating to fetching films data
export const FILM_FETCHING_COMPLETED = 'FILM_FETCHING_COMPLETED';
export const FILM_FETCHING_FAILED = 'FILM_FETCHING_FAILED';
export const START_FILM_FETCHING = 'START_FILM_FETCHING';
export const START_FETCH_MORE_FILMS = 'START_FETCH_MORE_FILMS';
export const FETCH_MORE_FILMS = 'FETCH_MORE_FILMS';

// Actions relating to film search history.
export const ADD_NEW_FILM_HISTORY_ITEM = 'ADD_NEW_FILM_HISTORY_ITEM';
export const REMOVE_FILM_HISTORY_ITEM = 'REMOVE_FILM_HISTORY_ITEM';
